export const GET_USER= 'GET_USER'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_START='AUTH_START'
export const LOG_OUT='LOG_OUT'
export const SIGN_UP = 'SIGN_UP'
export const Sign_UP_FAIL='Sign_UP_FAIL'
export const RESET='RESET'


export const GET_TASK_ACCESS = 'GET_TASK_ACCESS'
export const GET_TASK_FAIL = 'GET_TASK_FAIL'
export const GET_INIT='GET_INIT'
export const MARK_COMPLETED = 'MARK_COMPLETED'
export const HIDE_TOAST = 'HIDE_TOAST'